### ISSUE TITLE
AttributeError: module 'time' has no attribute 'clock'

### ISSUE THREAD

**Issue by Septan** [majora2007/plex-anime-tags#4]
```
D:\github\plex-anime-tags-main>python main.py
Processing "1001 Nights"
Matched on 1001 nights
1001 Nights is not in cache
Traceback (most recent call last):
  File "D:\github\plex-anime-tags-main\main.py", line 68, in <module>
    anidb.fetch_genres(anime, config_parser)
  File "D:\github\plex-anime-tags-main\providers\__init__.py", line 18, in rateLimitedFunction
    elapsed = time.clock() - lastTimeCalled[0]
AttributeError: module 'time' has no attribute 'clock'
```

**Comment by majora2007** [comment]
Let me take a look. What version of Python do you have?
